version: "3.5"

services:
    postgres_master:
        image: postgres:14.5-bullseye
        container_name: pg_master
        volumes:
          - ./postgres:/postgres/schema
        restart: unless-stopped
        environment:
            POSTGRES_DB: "task_tracker"
            POSTGRES_USER: "root"
            POSTGRES_PASSWORD: "root_password"
        ports:
          - "5432:5432"
        networks:
          - task_tracker_network

    webserver:
        image: nginx:alpine
        container_name: webserver
        volumes:
          - ./task_tracker_frontend:/usr/share/nginx/html
          - ./nginx:/etc/nginx/conf.d
        restart: unless-stopped
        tty: true
        ports:
          - "80:80"
          - "443:443"
        networks:
          - task_tracker_network

    backend:
        image: ubuntu:22.04
        build: task_tracker_backend/.
        depends_on:
            postgres_master:
                condition: service_started
        command: /bin/sh task_tracker_backend/startup.sh
        volumes:
          - ./task_tracker_backend:/backend/task_tracker_backend
          - ./migrations:/backend/migrations
          - ./logs/backend:/backend/logs
        restart: unless-stopped
        ports:
          - "6432:8000"
        networks:
          - task_tracker_network

networks:
    task_tracker_network:
        driver: bridge
